# Generated by Django 5.1.4 on 2024-12-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Merkki')),
                ('modelo', models.CharField(max_length=100, verbose_name='Malli')),
                ('color', models.CharField(max_length=50, verbose_name='Väri')),
                ('ano', models.IntegerField(verbose_name='Vuosi')),
                ('kilometraje', models.IntegerField(verbose_name='Kilometrimäärä')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Huomautukset')),
            ],
        ),
    ]
