# Generated by Django 5.1.4 on 2024-12-10 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasekoautolainaus', '0002_remove_auto_notas_auto_estado_alter_auto_ano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lainaus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opiskelija_etunimi', models.CharField(max_length=100)),
                ('opiskelija_sukunimi', models.CharField(max_length=100)),
                ('opiskelija_henkilotunnus', models.CharField(max_length=11)),
                ('opiskelija_id', models.CharField(max_length=20)),
                ('ajokorti_id', models.CharField(max_length=20)),
                ('lainaus_pvm', models.DateTimeField()),
                ('palautus_pvm', models.DateTimeField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lainaukset', to='rasekoautolainaus.auto')),
            ],
        ),
    ]
