# Generated by Django 5.1.4 on 2024-12-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasekoautolainaus', '0003_lainaus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lainaus',
            name='palautettu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lainaus',
            name='palautus_pvm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
