# Generated by Django 5.1.4 on 2024-12-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasekoautolainaus', '0004_lainaus_palautettu_alter_lainaus_palautus_pvm'),
    ]

    operations = [
        migrations.AddField(
            model_name='lainaus',
            name='luokka',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('CE', 'CE'), ('DE', 'DE'), ('T', 'T')], default='A', max_length=5),
        ),
    ]
