"""
Django settings for autolainaus_django project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Määritä polut projektin sisällä näin: BASE_DIR / 'alihakemisto'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Nopea aloituskehitysympäristön asetukset - ei sovellu tuotantoon
# Katso https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# TURVALLISUUSVAROITUS: pidä tuotannossa käytettävä salainen avain salassa!
SECRET_KEY = 'django-insecure-sqj@1nb%x=f-@%#&5c&x03()bl4ola!gq%y@qvau9$gqbf!-4i'

# TURVALLISUUSVAROITUS: älä käytä debug-tilaa tuotannossa!
DEBUG = True

ALLOWED_HOSTS = []


# Sovelluksen määrittely

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rasekoautolainaus',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'autolainaus_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Varmista, että tämä polku sisältää 'templates'-kansion
        'APP_DIRS': True,  # Mahdollistaa Djangoa etsimään malleja sovellusten kansioista
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'autolainaus_django.wsgi.application'


# Tietokanta
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Salasanan vahvistus
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Kansainvälistyminen
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Staattiset tiedostot (CSS, JavaScript, kuvat)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'  # Perus-URL staattisiin tiedostoihin pääsyyn

# Lisäpolut, joista etsitään staattisia tiedostoja
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Polku projektin staattisiin tiedostoihin
]

# Polku, johon staattiset tiedostot kerätään tuotannossa
STATIC_ROOT = BASE_DIR / "staticfiles"

# Oletus pääavainkentän tyyppi
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
